branches:
  only:
  - master
  - develop
language: objective-c
os: osx
osx_image: xcode10.2
xcode_workspace: Raytronome.xcworkspace
xcode_scheme: Raytronome
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X